services:
  pdnsadmin:
    image: pschiffe/pdns-admin:latest
    container_name: pdnsadmin
    restart: unless-stopped
    env_file:
      - .env
      - ../pdns-db/.env-admin
      - ../pdns-master/.env
    environment:
      PDNS_ADMIN_SQLA_DB_HOST: ${PDNS_DB_HOST}
      PDNS_ADMIN_SQLA_DB_PORT: ${PDNS_DB_PORT}
      PDNS_ADMIN_SQLA_DB_USER: ${PDNSADMIN_DB_USER}
      PDNS_ADMIN_SQLA_DB_PASSWORD: ${PDNSADMIN_DB_PASS}
      PDNS_ADMIN_SQLA_DB_NAME: ${PDNSADMIN_DB}
      PDNS_API_URL: http://${PDNS_MASTER_HOST}:8081/
      PDNS_API_KEY: ${PDNS_API_KEY}
      SSL_MAIN_DOMAIN: ${PDNSADMIN_DOMAIN}
      STRICT_HTTPS: "true"
    labels:
      - traefik.enable=true
      - traefik.docker.network=webproxy
      - traefik.http.routers.pdnsadmin.rule=Host(`${PDNSADMIN_DOMAIN}`)
      - traefik.http.routers.pdnsadmin.entrypoints=websecure
      - traefik.http.routers.pdnsadmin.tls.certresolver=cloudflare
      - traefik.http.services.pdnsadmin.loadbalancer.server.port=80
    volumes:
      - ./upload:/opt/powerdns-admin/upload
    networks:
      - webproxy

networks:
  webproxy:
    external: true
