services:
  pdnsadmin:
    image: ngoduykhanh/powerdns-admin:latest
    container_name: pdnsadmin
    restart: unless-stopped
    env_file:
      - .env
      - ../pdns-db/.env-admin
    environment:
      PDNS_DB_NAME: ${PDNSADMIN_DB}
      PDNS_DB_USERNAME: ${PDNSADMIN_DB_USER}
      PDNS_DB_PASSWORD: ${PDNSADMIN_DB_PASS}
    volumes:
      - ./uploads:/app/uploads
    labels:
      - traefik.enable=true
      - traefik.docker.network=webproxy
      - traefik.http.routers.pdnsadmin.rule=Host(`${PDNSADMIN_DOMAIN}`)
      - traefik.http.routers.pdnsadmin.entrypoints=websecure
      - traefik.http.routers.pdnsadmin.tls.certresolver=cloudflare
      - traefik.http.services.pdnsadmin.loadbalancer.server.port=80
    networks:
      - webproxy
      - pdns-net

networks:
  webproxy:
    external: true
  pdns-net:
    driver: bridge
