services:
  pdns:
    image: pschiffe/pdns-mysql:alpine
    container_name: pdns
    restart: unless-stopped
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=webproxy
      - traefik.http.routers.pdns.rule=Host(`${PDNS_DOMAIN}`)
      - traefik.http.routers.pdns.entrypoints=websecure
      - traefik.http.routers.pdns.tls.certresolver=cloudflare
      - traefik.http.services.pdns.loadbalancer.server.port=8081
    networks:
      - webproxy
      - default

  pdnsadmin:
    image: pschiffe/pdns-admin:latest
    container_name: pdnsadmin
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=webproxy
      - traefik.http.routers.pdnsadmin.rule=Host(`${PDNS_ADMIN_DOMAIN}`)
      - traefik.http.routers.pdnsadmin.entrypoints=websecure
      - traefik.http.routers.pdnsadmin.tls.certresolver=cloudflare
      - traefik.http.services.pdnsadmin.loadbalancer.server.port=8080
    networks:
      - webproxy
      - default
    depends_on:
      - pdns

  pdns-schema-init:
    image: mysql:9
    command: >
      sh -c "
      mysql -h ${PDNS_DB_HOST} -u${PDNS_DB_USER} -p${PDNS_DB_PASS} ${PDNS_DB_NAME} < /schema/schema.mysql.sql"
    volumes:
      - ./config/schema.mysql.sql:/schema/schema.mysql.sql:ro
    depends_on:
      - pdns
    restart: "no"

networks:
  webproxy:
    external: true
