services:
  pdns:
    image: pschiffe/pdns-mysql:alpine
    container_name: pdns
    restart: unless-stopped
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
      - "8081:8081"
    environment:
      TZ: Europe/Berlin
      # Enable API and webserver
      PDNS_api: "yes"
      PDNS_api-key: "${PDNS_API_KEY}"
      PDNS_webserver: "yes"
      PDNS_webserver_address: "0.0.0.0"
      # gmysql backend
      PDNS_launch: ${PDNS_LAUNCH}
      PDNS_gmysql_host: "${PDNS_DB_HOST}"
      PDNS_gmysql_port: "${PDNS_DB_PORT}"
      PDNS_gmysql_user: "${PDNS_DB_USER}"
      PDNS_gmysql_password: "${PDNS_DB_PASS}"
      PDNS_gmysql_dbname: "${PDNS_DB_NAME}"
      PDNS_webserver_allow_from: "0.0.0.0/0,::/0"
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=webproxy
      - traefik.http.routers.pdns.rule=Host(`${PDNS_DOMAIN}`)
      - traefik.http.routers.pdns.entrypoints=websecure
      - traefik.http.routers.pdns.tls.certresolver=cloudflare
      - traefik.http.services.pdns.loadbalancer.server.port=8081
    networks:
      - webproxy
      - default

  pdns-recursor:
    image: pschiffe/pdns-recursor:latest
    container_name: pdns-recursor
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./config/recursor.conf:/etc/pdns/recursor.conf
    restart: unless-stopped
    depends_on:
      - pdns
    networks:
      dockervlan:
        ipv4_address: ${PDNS_RECURSOR_VLAN_IP}

  pdnsadmin:
    image: pschiffe/pdns-admin:latest
    container_name: pdnsadmin
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=webproxy
      - traefik.http.routers.pdnsadmin.rule=Host(`${PDNS_ADMIN_DOMAIN}`)
      - traefik.http.routers.pdnsadmin.entrypoints=websecure
      - traefik.http.routers.pdnsadmin.tls.certresolver=cloudflare
      - traefik.http.services.pdnsadmin.loadbalancer.server.port=8080
    networks:
      - webproxy
      - default
    depends_on:
      - pdns

  pdns-schema-init:
    image: mysql:9
    command: >
      sh -c "
      mysql -h ${PDNS_DB_HOST} -u${PDNS_DB_USER} -p${PDNS_DB_PASS} ${PDNS_DB_NAME} < /schema/schema.mysql.sql"
    volumes:
      - ./config/schema.mysql.sql:/schema/schema.mysql.sql:ro
    depends_on:
      - pdns
    restart: "no"

networks:
  webproxy:
    external: true
  dockervlan:
    name: dpns-recursor
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: ${PDNS_RECURSOR_VLAN_SUBNET}
          ip_range: ${PDNS_RECURSOR_VLAN_IP}/32
          gateway: ${PDNS_RECURSOR_VLAN_GATEWAY}
