services:
  pdns-recursor:
    image: pschiffe/pdns-recursor:latest
    container_name: pdns-recursor
    env_file:
      - .env
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
