services:
  pdns:
    image: pschiffe/pdns-mysql:alpine
    container_name: pdns
    restart: unless-stopped
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    env_file:
      - .env
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf:ro
    networks:
      - webproxy
      - pdns

  pdns-schema-init:
    image: mysql:9
    command: sh /init/init-schema.sh
    env_file:
      - .env
    volumes:
      - ./config/init-schema.sh:/init/init-schema.sh:ro
      - ./config/schema.mysql.sql:/schema/schema.mysql.sql:ro
    depends_on:
      - pdns
    restart: "no"

networks:
  webproxy:
    external: true
  pdns:
    external: true
