services:
  pdns:
    image: pschiffe/pdns-mysql:alpine
    container_name: pdns
    restart: unless-stopped
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=webproxy
      - traefik.http.routers.pdns.rule=Host(`${PDNS_DOMAIN}`)
      - traefik.http.routers.pdns.entrypoints=websecure
      - traefik.http.routers.pdns.tls.certresolver=cloudflare
      - traefik.http.services.pdns.loadbalancer.server.port=8081
    networks:
      - webproxy
      - pdns

  pdns-schema-init:
    image: mysql:9
    command: >
      sh -c "
      mysql -h ${PDNS_gmysql_host} -u${PDNS_gmysql_user} -p${PDNS_gmysql_password} ${PDNS_gmysql_dbname} < /schema/schema.mysql.sql"
    volumes:
      - ./config/schema.mysql.sql:/schema/schema.mysql.sql:ro
    depends_on:
      - pdns
    restart: "no"

networks:
  webproxy:
    external: true
  pdns:
    external: true
