services:
  pdns:
    image: pschiffe/pdns-mysql:alpine
    container_name: pdns
    restart: unless-stopped
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    env_file:
      - .env
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf:ro
    networks:
      - webproxy
      - pdns

  pdns-schema-init:
    image: mysql:9
    command: >
      sh -c '
      echo "Waiting for MySQL to be ready...";
      until mysql -h ${PDNS_gmysql_host} -u${PDNS_gmysql_user} -p${PDNS_gmysql_password} -e "SELECT 1" ${PDNS_gmysql_dbname}; do
        echo "MySQL not ready, waiting...";
        sleep 2;
      done;
      echo "MySQL is ready. Importing schema...";
      mysql -h ${PDNS_gmysql_host} -u${PDNS_gmysql_user} -p${PDNS_gmysql_password} ${PDNS_gmysql_dbname} < /schema/schema.mysql.sql'

networks:
  webproxy:
    external: true
  pdns:
    external: true
