services:
  pdns-master:
    image: pschiffe/pdns-mysql:alpine
    container_name: pdns-master
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./config/pdns.conf:/etc/pdns/pdns.conf:ro
      - ./config/pdns.d:/etc/pdns/pdns.d:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=webproxy
      - traefik.http.routers.pdns-master.rule=Host(`${PDNS_MASTER_DOMAIN}`)
      - traefik.http.routers.pdns-master.entrypoints=websecure
      - traefik.http.routers.pdns-master.tls.certresolver=cloudflare
      - traefik.http.services.pdns-master.loadbalancer.server.port=8081
    networks:
      - webproxy
  pdns-schema-init:
    image: mysql:9
    command: >
      sh -c "
      mysql -h pdns-mysql -u${PDNS_DB_USER} -p${PDNS_DB_PASS} ${PDNS_DB_NAME} < /schema/schema.mysql.sql"
    volumes:
      - ./config/schema.mysql.sql:/schema/schema.mysql.sql:ro
    depends_on:
      - pdns-master
    restart: "no"

networks:
  webproxy:
    external: true
