services:
  db:
    image: mysql:9
    container_name: pdns-mysql
    env_file:
      - .env
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - pdnsnet

volumes:
  db_data:

networks:
  pdnsnet:
    driver: bridge
